### PR TITLE
Deinitialize

### PR DESCRIPTION
**Pull request by pati610**
Hi there,

here's my added func as referred to in Issue #17 on your repository page.

All the best,
Patrick Wingren

### CODE REVIEW

**Comment by pie6k** [comment]
Thanks for PR. Code is quite nested and complex as for what it does what in reality is just removing matching observers.

Would something like 

```
msobservers.deInitialize = function(selectorsToRemove) {
  /*
       * func for removing matching MutationSelectorObservers:
       *
       *    - all if var selectors is undefined, ex $.deInitialize();
       *
       *    - single selector if var selectors is a string,
       *       ex    $.deInitialize('.my-class');
       *
       *    - matching selectors if var selectors is an array,
       *       ex    var array = ['.my-class-one', '.my-class-2'];
       *             $.deInitialize(array);
       */

  if (selectorsToRemove === undefined) {
    msobservers = [];
    return;
  }

  if ($.isArray(selectorsToRemove)) {
    msobservers = msobservers.filter(observer => {
      return !selectorsToRemove.includes(oberver.selector);
    });
    return;
  }

  msobservers = msobservers.filter(observer => {
    return selectorsToRemove !== oberver.selector;
  });
  
};
```

do the job?

**Comment by pie6k** [comment]
Also, maybe API like:

```
const deinitializer = $.initialize(selector, cb);

// later on
deinitializer(); // now it's stopped

```

would be more 'elegant'? It is not forcing you to remember all the selectors and abstracts it away.

BTW. what is your use case for this?

**Comment by pati610** [comment]
I sure like your condensed version! But wouldn't that approach throw out the funcs themselves (initialize, deInitialize)?

The API approach is nice!

I'm using it for on-the-fly translations of dynamic, ajax-rendered content, so I need to catch every appearance of the elements, not only the first one. Thus every hashchange empties the selectors, and treats it like an initial page load.

**Comment by pati610** [comment]
And oh, I really like this script - it made everything I wanted to do so much easier!

**Comment by ZzZombo** [comment]
Your approach to your use case is VERY wrong. I won't say that the proposed functionality itself is bad, but you seem to misunderstand the core concepts of the MutationObserver API heavily. What you attempt to do is no better than iterating over all elements **each time** you detect some change, manually, and makes no real use of the API, while it allows you to avoid doing exactly that! It does allow you to get *every* change you asked it for, so just ask nicely, and you will both get every change and not overload the browser, so there is certainly no sense in "treating it like initial page load" – every time – if you can get away with working only with actually changed elements. I don't see why would translations require to do what you attempting to do or are already doing.

**Comment by pati610** [comment]
@ZzZombo I'm sure your way of using the MutationObserver API is VERY right. And you are also quite right that I'm not very familiar with the core concepts of the API, much less so than I'd like to be.

That said, I'm not particularly interested in doing things the way they are "supposed" to be done. In everything I do, I follow this simple logic: if it brings me the desired end results, its right - for me.

I love the jquery.initialize script because it lets me work effortlessly without diving in under the hood, which incidentally is pretty much what libraries and plugins are made for. I'm absolutely positive that you'd build the code for my task in a totally different way, but that don't really matters.

I aim less for how it "should" be done than for what it accomplishes. Being very happy with the performance right now (blazingly fast on-the-fly interactions in a quite complex DOM structure) I se no reason whatsoever to change my code logic just for the sake of it. And then off course there's the fact that you don't have the slightest idea of how my overall code is built. So I respectfully nod at your knowledge, and then I carry on with what I'm doing.

**Comment by dbezborodovrp** [comment]
Hi @ZzZombo, you are correct regarding the issue with #17 in that for every DOM mutation, the entire document is scanned. I have plans to allow an option (for backward compatibility) to limit the scan to the mutated element only to resolve this. Please make further suggestions to #17 and let us know your thoughts.

**Comment by dbezborodovrp** [comment]
I must admit, this `deinitializer` feature seems a little strange. I do not see a use case where one would want to remove an initializer. However, I am not opposed to the code change if the use case is valid.

@pati610, are you aware that if an element is initialized once, it will not be touched again subsequently? That is, if a mutation callback has previously matched its selector against an element and initialised it, it will remember that element and not initialise it more than once for further mutations? See:

```
        var callbackOnce = function () {
            if (seen.indexOf(this) == -1) {
                seen.push(this);
                $(this).each(callback);
            }   
        };  
```

**Comment by pie6k** [comment]
Agree with @dbezborodovrp . I still see use-case for de-initialization tho. Let's say you have some heavy app, and you simply want to 'pause' initialization for some time (eg. in time you have a lot of DOM mutations that you know will not be affected by initializer).

**Comment by pati610** [comment]
@pie6k just a quick repeat if my question earlier (I'm coming from PHP where nothing is copied by reference if not explicitly done so, so please bare with me): 

Wouldn't this line in your original reply 

```
if (selectorsToRemove === undefined) {
    msobservers = [];
    return;
  }
```
throw out the funcs if there's not a conditional checking, touching only the msobservers that aren't funcs?

**Comment by dbezborodovrp** [comment]
Hi @pati610

> to be sure that it happened every single time was to initialize at every dynamic partial load

How are you dynamically loading the partial? I have an application that loads partials using HTTP requests. For example, it will get an HTML partial using [`jQuery.get()`](https://api.jquery.com/jQuery.get/), pass it through [Handlebars](http://handlebarsjs.com/), then render the content in container using [`.html`](http://api.jquery.com/html/). Every time the partial is loaded, all the elements are reinitialized, because they have not been seen by the initializer. That is, the previous partial is removed from the DOM and new elements replace them. I have never had any problems with this approach.

> every call to history (-> on hashchange).

I no experience manipulating browser history, so I'm not sure how this would affect the initialiser.

I think it would be best if you can provide an isolated example of the bug, so that then we can have something tangible to work with. If you can provide a demonstration of the bug, please open a new Issue, since this pull request has been closed.

(Please also note that the codebase has been heavily rewritten in #17, #19, and #21, so nay merge requests will need to avoid conflicts there.)

**Pull request closed without merging**
