### PR TITLE
Simplify performance improvements.

### PR DESCRIPTION
**Pull request by dbezborodovrp**
This makes the recently introduced `scanMode` option unnecessary.  The plugin is now smart enough to determine the ideal `scanMode` based upon the complexity of the selector.

The standard scheme for querying the document object model is to query the mutated or any added nodes **and their descendants** for matching elements.

If the selector uses [**`+`**](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors) or [**`~`**](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_selectors) sibling combinators (such as `div ~ p`, or `thead + tbody`), then the observer will check the mutated or added node, its descendants, **and its siblings** for a match.

This will mean that users of jQuery.initialize will not need to understand unnecessary internals of the plugin in order to take advantage of the performance improvements introduced in #19.

As mentioned below, if the selector does not use any of [Class selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors), [ID selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/ID_selectors), [Attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), or pseudo-classes then attribute mutations will not be subscribed to, giving a further performance improvement.

### CODE REVIEW

**Comment by dbezborodovrp** [comment]
This pull request will also ignore attribute mutations if the selector does not use any of [Class selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors), [ID selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/ID_selectors), or [Attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors).

**Comment by dbezborodovrp** [comment]
Hmm, don't merge yet. Testing.

**Comment by dbezborodovrp** [comment]
Fixed a small bug found when testing in my application. (fa800ad)

**Comment by pie6k** [comment]
Merged. Thanks!

**Comment by dbezborodovrp** [comment]
We should probably tag and [release a new version on NPM](https://docs.npmjs.com/getting-started/publishing-npm-packages) at some point. Installing via NPM currently installs an older version.

**Pull request merged**
